# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 16:05:58 2025

@author: Haliz369
"""

# -*- coding: utf-8 -*-
"""MyVITConv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-F7t_qCi8NhQV4UnUTAx9Stat5q5rbzc

# Mountin Google Drive
"""

# # Commented out IPython magic to ensure Python compatibility.
# ####### Mounting your google drive hamed
# from google.colab import drive
# drive.mount('/content/drive')

# ####### Data address in google drive

import os
os.chdir("D:\\Thesis-PhD\\SemanticSegmentation\\NC13")

# # %cd /content/drive/MyDrive/Colab Notebooks/DeepLearning-HSI classification/My ViT+Conv/Image
# # %cd /content/drive/MyDrive/DeepLearning-HSI classification/My ViT+Conv/Image

# """# Import Libraries"""

# # !pip install earthpy
# # !pip install tqdm
# pip install rasterio
# pip install einops
# pip install torchinfo


import matplotlib.pyplot as plt

import numpy as np
# import earthpy.plot as ep
import seaborn as sns
# import earthpy.spatial as es

import plotly.graph_objects as go
import plotly.express as px

from scipy.io import loadmat

import pandas as pd

from sklearn.preprocessing import minmax_scale,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score,
                             confusion_matrix, classification_report)


import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, TensorDataset
from torch import cat
import einops




from tqdm import tqdm
from numpy.random import seed
from time import time
import rasterio
# seed(11)



#%% Functions
# 
from Image_Preproc import ExtractPatches, ScaleData

#%% Load Data


dir_path = 'D:\\Thesis-PhD\\SemanticSegmentation\\NC13\\Image\\'


data1 = np.load(dir_path+'NC13.npz')

# Access the variables
data = data1['data']
gt = data1['GT']
data = np.float16(data)

gt[gt == 0] = 255
gt[gt != 255] -= 1


min_value = np.min(data)
max_value = np.max(data)

data = ScaleData(data,min_value,max_value)

# plt.imshow(gt, cmap='nipy_spectral')
#%% patchify
from einops import rearrange

h = data.shape[1]
w = data.shape[2]
patch_size=32
pad_h = patch_size * (h//patch_size + 1) - h  # Padding needed for height
pad_w = patch_size * (w//patch_size + 1) - w  # Padding needed for width

data = np.pad(data, ((0, 0), (0, pad_h), (0, pad_w)), mode='constant')
gt = np.pad(gt, ((0, pad_h), (0, pad_w)), mode='constant',constant_values=255)


# ####### no overlap
# data = rearrange(data,"c (h p1) (w p2) -> (h w) c p1 p2",p1=patch_size,p2=patch_size)
# gt = rearrange(gt,"(h p1) (w p2) -> (h w) p1 p2",p1=patch_size,p2=patch_size)

####### with overlap
from Image_Preproc import extract_overlapping_patches
stride=8
data = extract_overlapping_patches(data, patch_size, stride)
gt = extract_overlapping_patches(gt, patch_size, stride)
#######################################

filt=np.sum(gt<100,axis=(1,2))
a = filt>((patch_size**2)*0.3) # filter data. select those who have 30% of lables in tself

data = data[a]
gt = gt [a]

print(f"dimension of patchified data : {data.shape}")
print(f"dimension of patchified gt : {gt.shape}")



#%% Patch Visualization 

# import earthpy.plot as ep
# # Select random indices
# num_samples = 5  # Number of patches to plot
# random_indices = np.random.choice(data.shape[0], num_samples, replace=False)

# # Plot the selected patches
# fig, axes = plt.subplots(num_samples, 2, figsize=(8, 2 * num_samples))
# R, G, B = 140, 54, 24
# for i, idx in enumerate(random_indices):
#     # Extract the RGB bands from the hyperspectral data
#     rgb_patch = np.stack([data[idx, R,:,:], data[idx, G,:,:], data[idx, B,:,:]], axis=0)  # (H, W, 3)
    
#     # Normalize for better visualization (optional)
#     rgb_patch = (rgb_patch - rgb_patch.min()) / (rgb_patch.max() - rgb_patch.min())

#     # Plot RGB image
#     ep.plot_rgb(rgb_patch, figsize=(4, 4), stretch=True, ax=axes[i, 0])
#     axes[i, 0].set_title(f"RGB Patch {idx}")

#     # Plot Ground Truth
#     axes[i, 1].imshow(gt[idx], cmap='nipy_spectral')
#     axes[i, 1].set_title(f"GT Patch {idx}")
#     axes[i, 1].axis("off")

# plt.tight_layout()
# plt.show()


#%% train valiation split

from sklearn.model_selection import train_test_split


# Split the first axis (axis=0) into training and validation sets
train_idx, val_idx = train_test_split(np.arange(data.shape[0]), test_size=0.2, random_state=42)

train_data = data[train_idx,:,:,:]
train_gt = gt[train_idx,:,:]
print(f"dimension of train data : {train_data.shape}")
print(f"dimension of train gt : {train_gt.shape}")

validation_data = data[val_idx,:,:,:]
validation_gt = gt[val_idx,:,:]
print(f"dimension of validation data : {validation_data.shape}")
print(f"dimension of validation gt : {validation_gt.shape}")
#%% Model
import torch
import torch.nn as nn
import torch.nn.functional as F

class SimpleSegmentationModel(nn.Module):
    def __init__(self, in_channels=3, out_channels=1, init_features=32):
        super(SimpleSegmentationModel, self).__init__()
        
        features = init_features
        
        # Encoder (Downsampling)
        self.encoder1 = self._block(in_channels, features, name="enc1")
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        self.encoder2 = self._block(features, features * 2, name="enc2")
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Bottleneck
        self.bottleneck = self._block(features * 2, features * 4, name="bottleneck")
        
        # Decoder (Upsampling)
        self.upconv2 = nn.ConvTranspose2d(
            features * 4, features * 2, kernel_size=2, stride=2
        )
        self.decoder2 = self._block(features * 4, features * 2, name="dec2")
        self.upconv1 = nn.ConvTranspose2d(
            features * 2, features, kernel_size=2, stride=2
        )
        self.decoder1 = self._block(features * 2, features, name="dec1")
        
        # Final layer
        self.conv = nn.Conv2d(
            in_channels=features, out_channels=out_channels, kernel_size=1
        )

    def forward(self, x):
        # Encoder
        enc1 = self.encoder1(x)
        enc2 = self.encoder2(self.pool1(enc1))
        
        # Bottleneck
        bottleneck = self.bottleneck(self.pool2(enc2))
        
        # Decoder
        dec2 = self.upconv2(bottleneck)
        dec2 = torch.cat((dec2, enc2), dim=1)
        dec2 = self.decoder2(dec2)
        dec1 = self.upconv1(dec2)
        dec1 = torch.cat((dec1, enc1), dim=1)
        dec1 = self.decoder1(dec1)
        
        # Final output
        return self.conv(dec1)  # Use sigmoid for binary segmentation

    def _block(self, in_channels, features, name):
        return nn.Sequential(
            nn.Conv2d(
                in_channels=in_channels,
                out_channels=features,
                kernel_size=3,
                padding=1,
                bias=False,
            ),
            nn.BatchNorm2d(num_features=features),
            nn.ReLU(inplace=True),
            nn.Conv2d(
                in_channels=features,
                out_channels=features,
                kernel_size=3,
                padding=1,
                bias=False,
            ),
            nn.BatchNorm2d(num_features=features),
            nn.ReLU(inplace=True),
        )
    
#%%
# input_shape = train_data[0].shape                       # input shape of  model  e.g.(200,21,21)
# nb_classes= np.max(gt)                         # output shape of model

# model = SimpleSegmentationModel(in_channels=input_shape[0], out_channels=nb_classes)   

# x = torch.randn((1, input_shape[0], 64, 64))  # Example input (batch_size=1, channels=3, height=256, width=256)
# x.type
# preds = model(x)

# # train_data = data[train_idx,:,:,:]
# # train_gt = gt[train_idx,:,:]
# a = torch.tensor(train_data, dtype=torch.float32)
# outputs = model(a)

# b = torch.tensor(train_gt, dtype=torch.int32).long() 

# criterion = nn.CrossEntropyLoss(ignore_index=255 )#
 
# loss = criterion(outputs, b) #.long()


#%% to gpu    

# from torch.utils.data import DataLoader, TensorDataset
# from torch import cat
batch_size=128

# Check if a GPU is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# device = torch.device("cuda:0,1" if torch.cuda.is_available() else "cpu")
# Convert NumPy arrays to PyTorch tensors
train_data = torch.tensor(train_data, dtype=torch.float32).to(device,)
train_gt = torch.tensor(train_gt,dtype=torch.int32).to(device)
validation_data = torch.tensor(validation_data, dtype=torch.float32).to(device)
validation_gt = torch.tensor(validation_gt,dtype=torch.int32).to(device)

train_dataset = TensorDataset(train_data, train_gt)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataset = TensorDataset(validation_data, validation_gt)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)



#%% model definition

input_shape = train_data[0].shape                       # input shape of  model  e.g.(200,21,21)
nb_classes= 13                        # output shape of model

model = SimpleSegmentationModel(in_channels=input_shape[0], out_channels=nb_classes)   

from torchinfo import summary
input = (1,) + input_shape

print(summary(model, input))


# criterion = nn.CrossEntropyLoss()
criterion = nn.CrossEntropyLoss(ignore_index=255 )#
# optimizer = optim.Adam(model.parameters())  #0.9287451327373675, lr= 0.01 , weight_decay=0.0005
optimizer = optim.Adam(model.parameters(),weight_decay=1e-4)#,lr= 0.0005, weight_decay=1e-4)  # lr= 0.0005, weight_decay=1e-4



model = model.to(device)  
# model = nn.DataParallel(model).to(device) 

#%%
def calculate_accuracy(output, target, ignore_index=255):
    """
    Calculate pixel-wise accuracy.

    Args:
        output (torch.Tensor): Model output of shape [batch, num_classes, height, width].
        target (torch.Tensor): Ground truth labels of shape [batch, height, width].
        ignore_index (int): Index to ignore in the target (e.g., background).

    Returns:
        accuracy (float): Pixel-wise accuracy.
    """
    # Get the predicted class for each pixel
    preds = torch.argmax(output, dim=1)  # Shape: [batch, height, width]

    # Create a mask to ignore the background class
    if ignore_index is not None:
        mask = (target != ignore_index)
    else:
        mask = torch.ones_like(target, dtype=torch.bool)

    # Count the number of correct predictions (excluding background)
    correct = (preds[mask] == target[mask]).sum().item()

    # Total number of pixels (excluding background)
    total = mask.sum().item()

    # Calculate accuracy
    accuracy = correct / (total + 1e-6)  # Add small epsilon to avoid division by zero
    return accuracy

def calculate_iou(output, target, num_classes, ignore_index=255):
    """
    Calculate Intersection over Union (IoU) for each class.

    Args:
        output (torch.Tensor): Model output of shape [batch, num_classes, height, width].
        target (torch.Tensor): Ground truth labels of shape [batch, height, width].
        num_classes (int): Number of classes.
        ignore_index (int): Index to ignore in the target (e.g., background).

    Returns:
        iou (torch.Tensor): IoU for each class.
    """
    # Get the predicted class for each pixel
    preds = torch.argmax(output, dim=1)  # Shape: [batch, height, width]

    # Initialize tensors to store intersection and union for each class
    intersection = torch.zeros(num_classes)
    union = torch.zeros(num_classes)

    # Calculate intersection and union for each class
    for cls in range(num_classes):
        # Mask for predicted and target classes
        pred_mask = (preds == cls)
        target_mask = (target == cls)

        # Ignore pixels with ignore_index
        if ignore_index is not None:
            target_mask = target_mask & (target != ignore_index)
            pred_mask = pred_mask & (target != ignore_index)

        # Update intersection and union
        intersection[cls] = (pred_mask & target_mask).sum().item()
        union[cls] = (pred_mask | target_mask).sum().item()

    # Avoid division by zero for classes not present in the target
    iou = intersection / (union + 1e-6)  # Add small epsilon to avoid division by zero
    return iou

#%% Train
from torch.optim import lr_scheduler
# Define the learning rate scheduler
# scheduler = lr_scheduler.StepLR(optimizer, step_size=30, gamma=0.1)
# scheduler = lr_scheduler.ExponentialLR(optimizer, gamma=0.95)
scheduler = lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)

# Lists to store training and validation loss values for each epoch
train_loss_values = []
val_loss_values = []

nb_epoch=100
best_val_loss = float('inf')
# best_val_accuracy = 0

for epoch in range(nb_epoch):
    start_time = time()
    
    model.train()
    train_loss = 0

    for inputs, labels in train_loader :  #tqdm(train_loader)
        optimizer.zero_grad()
        outputs = model(inputs)
       
        loss = criterion(outputs, labels.long())
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
    # Step the learning rate scheduler
    scheduler.step()

    # Validation
    model.eval()
    val_loss = 0
    total_accuracy  = 0
    total_iou = torch.zeros(nb_classes)
    total_samples  = 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            outputs = model(inputs)
            loss = criterion(outputs, labels.long())
            val_loss += loss.item()
            
            # Calculate IoU and accuracy
            iou = calculate_iou(outputs, labels, nb_classes, ignore_index=255)
            accuracy = calculate_accuracy(outputs, labels, ignore_index=255)
            
            total_iou += iou
            total_accuracy += accuracy
            total_samples += 1

    val_loss /= len(val_loader)
    mean_iou = (total_iou / total_samples).mean().item()  # Mean IoU across all classes
    mean_accuracy = total_accuracy / total_samples  # Mean accuracy
    
    epoch_time = time() - start_time 
    print(f'Epoch [{epoch + 1}/{nb_epoch}], Val Loss: {val_loss:.4f}, Accuracy: {mean_accuracy:.4f}, IOU: {mean_iou:.4f}, Time: {epoch_time:.2f}')

    # # Save the best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), 'best_model.pth')



# model.load_state_dict(torch.load('best_model.pth'))
# model.eval()

# result=[]
# val_loss = 0
# total_accuracy  = 0
# total_iou = torch.zeros(nb_classes)
# total_samples  = 0
# with torch.no_grad():
#     for inputs, labels in val_loader:
#         outputs = model(inputs)
#         loss = criterion(outputs, labels.long())
#         val_loss += loss.item()
        
#         # Calculate IoU and accuracy
#         iou = calculate_iou(outputs, labels, nb_classes, ignore_index=255)
#         accuracy = calculate_accuracy(outputs, labels, ignore_index=255)
        
#         total_iou += iou
#         total_accuracy += accuracy
#         total_samples += 1
        
#         preds = torch.argmax(outputs, dim=1)
#         result.append(preds.cpu().numpy())

# val_loss /= len(val_loader)
# mean_iou = (total_iou / total_samples).mean().item()  # Mean IoU across all classes
# mean_accuracy = total_accuracy / total_samples  # Mean accuracy
    
# result = np.concatenate(result)


#%%

# import earthpy.plot as ep
# # Select random indices
# num_samples = 5  # Number of patches to plot
# random_indices = np.random.choice(result.shape[0], num_samples, replace=False)

# # Plot the selected patches
# fig, axes = plt.subplots(num_samples, 3, figsize=(8, 2 * num_samples))
# R, G, B = 140, 54, 24

# data = validation_data.cpu().numpy()
# gt = validation_gt.cpu().numpy()
# for i, idx in enumerate(random_indices):
#     # Extract the RGB bands from the hyperspectral data
#     rgb_patch = np.stack([data[idx, R,:,:], data[idx, G,:,:], data[idx, B,:,:]], axis=0)  # (H, W, 3)
    
#     # Normalize for better visualization (optional)
#     rgb_patch = (rgb_patch - rgb_patch.min()) / (rgb_patch.max() - rgb_patch.min())

#     # Plot RGB image
#     ep.plot_rgb(rgb_patch, figsize=(4, 4), stretch=True, ax=axes[i, 0])
#     axes[i, 0].set_title(f"RGB Patch {idx}")

#     # Plot Ground Truth
#     axes[i, 1].imshow(gt[idx], cmap='nipy_spectral')
#     axes[i, 1].set_title(f"GT Patch {idx}")
#     axes[i, 1].axis("off")
    
#     # Plot Ground Truth
#     axes[i, 2].imshow(result[idx], cmap='nipy_spectral')
#     axes[i, 2].set_title(f"Pred Patch {idx}")
#     axes[i, 2].axis("off")

# plt.tight_layout()
# plt.show()



#%%
model = SimpleSegmentationModel(in_channels=270, out_channels=13).to(device)   
model.load_state_dict(torch.load('best_model.pth'))
model.eval()

# data = data1['data']
# data = np.float16(data)

data = torch.tensor(data, dtype=torch.float32).to(device,)
data = data.unsqueeze(0)



with torch.no_grad():
    outputs = model(data)
    
preds = torch.argmax(outputs, dim=1).squeeze(0).cpu().numpy() 
preds[gt==255]=-1

preds = preds+1
plt.figure()
plt.imshow(preds, cmap='nipy_spectral')  

plt.figure()
plt.imshow(gt, cmap='nipy_spectral')  


# num_classes=13
# preds = torch.argmax(outputs, dim=1).squeeze(0).cpu().numpy() 
# target=gt
# ignore_index=255
# # Get the predicted class for each pixel
# # preds = torch.argmax(output, dim=1)  # Shape: [batch, height, width]

# # Initialize tensors to store intersection and union for each class
# intersection = np.zeros(num_classes)
# union = np.zeros(num_classes)

# # Calculate intersection and union for each class
# for cls in range(num_classes):
#     # Mask for predicted and target classes
#     pred_mask = (preds == cls)
#     target_mask = (target == cls)

#     # Ignore pixels with ignore_index
#     if ignore_index is not None:
#         target_mask = target_mask & (target != ignore_index)
#         pred_mask = pred_mask & (target != ignore_index)

#     # Update intersection and union
#     intersection[cls] = (pred_mask & target_mask).sum().item()
#     union[cls] = (pred_mask | target_mask).sum().item()

# # Avoid division by zero for classes not present in the target
# iou = intersection / (union + 1e-6)  # Add small epsilon to avoid division by zero
# # return iou






# intersection = np.zeros(13)
# union = np.zeros(13)

# # Calculate intersection and union for each class
# for cls in range(13):
#     # Mask for predicted and target classes
#     pred_mask = (preds == cls+1)
#     target_mask = (gt == cls+1)

#     # # Ignore pixels with ignore_index
#     # if ignore_index is not None:
#     #     target_mask = target_mask & (target != ignore_index)
#     #     pred_mask = pred_mask & (target != ignore_index)

#     # Update intersection and union
#     intersection[cls] = (pred_mask & target_mask).sum().item()
#     union[cls] = (pred_mask | target_mask).sum().item()

# # Avoid division by zero for classes not present in the target
# iou = intersection / (union + 1e-6)  # Add small epsilon to avoid division by zero
